name = "FreqTables"
uuid = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
version = "0.4.5"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CategoricalArrays = "0.8, 0.9, 0.10"
DataFrames = "0.21, 0.22, 1"
Missings = "0.4, 1.0"
NamedArrays = "0.9.1, 0.10"
Tables = "1"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames"]
